spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/STUDY_DB
    username: postgres
    password: postgres


todo:
 sysdate: # システム日付
   value: 2025-10-14
   useflag: true  # true ;valueの値を使用